apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: debug-svc-01
  labels:
    app: data-service
    tier: data  # This label is intentionally different from the service selector
spec:
  replicas: 2  # Run two instances of our data service for redundancy
  selector:
    matchLabels:
      app: data-service
      tier: data
  template:
    metadata:
      labels:
        app: data-service
        tier: data  # The service selector is looking for 'tier: database' instead
    spec:
      containers:
      - name: data-api
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http       # Named port for better readability
        volumeMounts:
        - name: data-config
          mountPath: /etc/nginx/conf.d
        resources:
          # Setting reasonable resource limits
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: data-config
        configMap:
          name: data-service-config 