apiVersion: v1
kind: Service
metadata:
  name: memory-app-service
  namespace: debug-rm-01
spec:
  selector:
    app: memory-intensive-app
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP 